### ISSUE TITLE
 FATA 004 Error on outputBlock: could not create bootstrapper: could not create channel group: error adding policies to channel group: no policies defined

### ISSUE THREAD

**Issue by dhruvaj-patil** [Salmandabbakuti/hlf-chaincodeTest#1]
I am trying to setup this project to get a hang of hyperledger fabric. I am stuck on creation of policies and I tried searching through the documentation on HL-fabric but I couldn't seem to get my head around it. Any help or resources regarding this could be helpful. Thank you.

**Comment by Salmandabbakuti** [comment]
Hi @dhruvaj-patil ,

Sorry for the late reply. Earlier versions of fabric use default channel configurations for channel even if we don't specify them in our ```configtx.yml```. after1.4, we must define policies. So direct solution to your problem is that, use pre-generated certificates in this repository or specify channel policies in ```configtx.yaml``` and generate certificates again.

**Comment by 20kwok** [comment]
Hello, i got the following error after executed  'configtxgen -profile AcmeOrdererGenesis -channelID ordererchannel -outputBlock acme-genesis.block' 

 FATA 004 Error on outputBlock: could not create bootstrapper: could not create channel group: error adding policies to channel group: no policies defined

My Profile session in my configtx.yaml is as follow:

Profiles:

  AcmeOrdererGenesis:
      Orderer:
          <<: *OrdererDefaults
          Organizations:
              - *Orderer
      Consortiums:
          AirlineConsortium:
              Organizations:
                  - *Org1
  AcmeChannel:
    Consortium: AirlineConsortium
    Application:
        <<: *ApplicationDefaults
        Organizations:
            - *Org1

**Comment by ParitaNinjatech** [comment]
Custom policies are defined. Is it possible?
